version: '3.3'
services:
  cache:
    image: memcached:latest
    ports:
      - "11211:11211"
  database:
    image: postgres:latest
    env_file:
      - database.env
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  data:
