version: '3.3'
services:
  cache:
    image: memcached:latest
    ports:
      - "11211:11211"
  database:
    image: postgres:latest
    env_file:
      - database.env
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  server:
    build: .
    environment:
      - MEMCACHED_HOST=cache
      - POSTGRES_HOST=database
    depends_on:
      - cache
      - database
    ports:
      - "8080:8080"
volumes:
  data:
